#!/bin/sh

echo "Criando diretórios..."
mkdir userdata
echo "Criando virtual environment..."
python -m venv env
source env/bin/activate
echo "Instalando dependências..."
pip install -r requirements.txt
echo "Add an OpenAI API key to config.ini."
